log_dir = "runs/GAN_training"
name = "anogan"
n_epochs = 200
batch_size = 8
lr = 0.0002
b1 = 0.5
b2 = 0.999
latent_dim = 100
img_size = 512
channels = 3
n_critic = 5
sample_interval = 400
training_label = 0
split_rate = 0.8
lambda_gp = 10
object = "toothbrush"